-- 图书管理系统初始化数据
SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
USE library_db;

-- ----------------------------
-- 初始化角色
-- ----------------------------
INSERT INTO roles (id, role_name, role_code, description) VALUES
(1, '管理员', 'ADMIN', '系统管理员，拥有所有权限'),
(2, '普通用户', 'USER', '普通用户，可以借阅图书');

-- ----------------------------
-- 初始化权限
-- ----------------------------
INSERT INTO permissions (id, permission_name, permission_code, resource_type, parent_id, sort_order) VALUES
-- 一级菜单
(1, '仪表盘', 'dashboard', 'menu', 0, 1),
(2, '图书管理', 'book', 'menu', 0, 2),
(3, '借阅管理', 'borrow', 'menu', 0, 3),
(4, '用户管理', 'user', 'menu', 0, 4),
(5, '系统管理', 'system', 'menu', 0, 5),
-- 图书管理子菜单
(21, '图书列表', 'book:list', 'menu', 2, 1),
(22, '分类管理', 'book:category', 'menu', 2, 2),
(23, '库存预警', 'book:stock', 'menu', 2, 3),
-- 图书操作按钮
(201, '新增图书', 'book:create', 'button', 2, 1),
(202, '编辑图书', 'book:update', 'button', 2, 2),
(203, '删除图书', 'book:delete', 'button', 2, 3),
(204, '导入图书', 'book:import', 'button', 2, 4),
(205, '导出图书', 'book:export', 'button', 2, 5),
-- 借阅管理子菜单
(31, '借阅记录', 'borrow:list', 'menu', 3, 1),
(32, '逾期列表', 'borrow:overdue', 'menu', 3, 2),
(33, '我的借阅', 'borrow:my', 'menu', 3, 3),
-- 借阅操作按钮
(301, '借阅图书', 'borrow:create', 'button', 3, 1),
(302, '归还图书', 'borrow:return', 'button', 3, 2),
(303, '续借图书', 'borrow:renew', 'button', 3, 3),
-- 用户管理子菜单
(41, '用户列表', 'user:list', 'menu', 4, 1),
(42, '角色管理', 'user:role', 'menu', 4, 2),
-- 用户操作按钮
(401, '新增用户', 'user:create', 'button', 4, 1),
(402, '编辑用户', 'user:update', 'button', 4, 2),
(403, '删除用户', 'user:delete', 'button', 4, 3),
(404, '重置密码', 'user:reset', 'button', 4, 4),
-- 系统管理子菜单
(51, '操作日志', 'system:log', 'menu', 5, 1),
(52, '系统配置', 'system:config', 'menu', 5, 2);

-- ----------------------------
-- 初始化角色权限 - 管理员拥有所有权限
-- ----------------------------
INSERT INTO role_permissions (role_id, permission_id) VALUES
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5),
(1, 21), (1, 22), (1, 23),
(1, 201), (1, 202), (1, 203), (1, 204), (1, 205),
(1, 31), (1, 32), (1, 33),
(1, 301), (1, 302), (1, 303),
(1, 41), (1, 42),
(1, 401), (1, 402), (1, 403), (1, 404),
(1, 51), (1, 52);

-- 普通用户权限
INSERT INTO role_permissions (role_id, permission_id) VALUES
(2, 1), (2, 2), (2, 3),
(2, 21), (2, 33),
(2, 301), (2, 302), (2, 303);

-- ----------------------------
-- 初始化用户 (密码: 123456)
-- BCrypt hash for "123456" generated by Spring Security BCryptPasswordEncoder
-- ----------------------------
INSERT INTO users (id, username, password, email, phone, status) VALUES
(1, 'admin', '$2a$10$ORc2SePfUREE.2tY96XE3eIxDErx7c5txSGA1H2p.O.8EYyNwilH2', 'admin@library.com', '13800000001', 1),
(2, 'user', '$2a$10$ORc2SePfUREE.2tY96XE3eIxDErx7c5txSGA1H2p.O.8EYyNwilH2', 'user@library.com', '13800000002', 1),
(3, 'test', '$2a$10$ORc2SePfUREE.2tY96XE3eIxDErx7c5txSGA1H2p.O.8EYyNwilH2', 'test@library.com', '13800000003', 1);

-- ----------------------------
-- 初始化用户角色
-- ----------------------------
INSERT INTO user_roles (user_id, role_id) VALUES
(1, 1),  -- admin -> 管理员
(2, 2),  -- user -> 普通用户
(3, 2);  -- test -> 普通用户

-- ----------------------------
-- 初始化图书分类
-- ----------------------------
INSERT INTO categories (id, name, description, parent_id, sort_order) VALUES
(1, '文学', '文学类图书', 0, 1),
(2, '科技', '科技类图书', 0, 2),
(3, '教育', '教育类图书', 0, 3),
(4, '历史', '历史类图书', 0, 4),
(5, '艺术', '艺术类图书', 0, 5),
(11, '小说', '小说类图书', 1, 1),
(12, '诗歌', '诗歌类图书', 1, 2),
(13, '散文', '散文类图书', 1, 3),
(21, '计算机', '计算机类图书', 2, 1),
(22, '物理', '物理类图书', 2, 2),
(23, '化学', '化学类图书', 2, 3),
(31, '考试', '考试辅导类图书', 3, 1),
(32, '教材', '教材类图书', 3, 2);

-- ----------------------------
-- 初始化图书
-- ----------------------------
INSERT INTO books (isbn, title, author, publisher, publish_date, price, category_id, description, total_stock, available_stock, location, status) VALUES
('978-7-111-40701-0', 'Java编程思想', 'Bruce Eckel', '机械工业出版社', '2007-06-01', 108.00, 21, 'Java领域的经典著作，详细阐述Java的核心概念和编程技巧。', 10, 8, 'A区-01-01', 1),
('978-7-121-31882-5', 'Spring实战', 'Craig Walls', '人民邮电出版社', '2016-09-01', 89.00, 21, 'Spring框架的权威指南，涵盖Spring Boot、Spring Cloud等内容。', 8, 6, 'A区-01-02', 1),
('978-7-115-39317-0', '深入理解Java虚拟机', '周志明', '机械工业出版社', '2019-12-01', 129.00, 21, '全面深入地讲解Java虚拟机的工作原理。', 6, 4, 'A区-01-03', 1),
('978-7-115-29382-8', 'JavaScript高级程序设计', 'Nicholas C. Zakas', '人民邮电出版社', '2012-03-01', 99.00, 21, 'JavaScript领域的红宝书，前端开发必读。', 12, 10, 'A区-02-01', 1),
('978-7-302-44064-9', 'Python编程：从入门到实践', 'Eric Matthes', '人民邮电出版社', '2016-07-01', 89.00, 21, 'Python入门经典教程，适合编程初学者。', 15, 12, 'A区-02-02', 1),
('978-7-5086-6895-6', '三体', '刘慈欣', '重庆出版社', '2008-01-01', 68.00, 11, '中国科幻里程碑之作，获雨果奖。', 20, 15, 'B区-01-01', 1),
('978-7-02-009882-0', '红楼梦', '曹雪芹', '人民文学出版社', '1996-12-01', 59.80, 11, '中国古典四大名著之一。', 10, 8, 'B区-01-02', 1),
('978-7-5447-5735-2', '百年孤独', '加西亚·马尔克斯', '南海出版公司', '2017-08-01', 55.00, 11, '魔幻现实主义代表作。', 8, 6, 'B区-01-03', 1),
('978-7-5327-4746-0', '活着', '余华', '作家出版社', '2012-08-01', 29.00, 11, '讲述一个人一生的苦难与抗争。', 12, 9, 'B区-02-01', 1),
('978-7-80165-832-5', '明朝那些事儿', '当年明月', '中国海关出版社', '2009-04-01', 358.00, 4, '明朝三百年历史的趣味解读。', 6, 5, 'C区-01-01', 1);

-- ----------------------------
-- 初始化系统配置
-- ----------------------------
INSERT INTO system_config (config_key, config_value, description) VALUES
('default_borrow_days', '30', '默认借阅天数'),
('max_renew_times', '1', '最大续借次数'),
('renew_days', '30', '续借天数'),
('overdue_fine_per_day', '0.5', '逾期每天罚款金额(元)'),
('reminder_days_before', '3', '到期提醒提前天数'),
('stock_warning_threshold', '5', '库存预警阈值'),
('max_borrow_count', '5', '最大借阅数量');
